version: '3.5'
services:
  front:
    image: yuanmomo/webase-front:${WEBASE_DOCKER_TAG}
    container_name: front
    restart: always
    network_mode: "host"
    #networks:
    #  - webase_network
    depends_on:
      - "node3"
    ports:
      - "5002:5002"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    volumes:
      - ./conf/front-application.yml:/dist/conf/application-docker.yml
      - ./h2:/dist/h2/
      - ./log/front:/log
      - ~/fisco/nodes/127.0.0.1/sdk/ca.crt:/dist/conf/ca.crt
      - ~/fisco/nodes/127.0.0.1/sdk/node.crt:/dist/conf/node.crt
      - ~/fisco/nodes/127.0.0.1/sdk/node.key:/dist/conf/node.key

  webase-node-manager:
    image: yuanmomo/webase-node-manager:${WEBASE_DOCKER_TAG}
    container_name: webase-node-manager
    restart: always
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    volumes:
      - ./log/node-manager:/log
      - ./conf/node-manager-application.yml:/dist/conf/application-docker.yml
    ports:
      - "5001:5001"
    depends_on:
      - "mysql"
    network_mode: "host"
    #networks:
    #  - webase_network

  mysql-manager:
    #构建mysql镜像
    image: yuanmomo/webase-mysql:${WEBASE_MYSQL_TAG}
    container_name: mysql-manager-server # 容器名
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #root管理员用户密码
      MYSQL_DATABASE: webasenodemanager
      MYSQL_USER: defaultAccount
      MYSQL_PASSWORD: defaultPassword
    ports:
      - '3306:3306'  #host物理直接映射端口为3306
    volumes:
      #mysql数据库挂载到host物理机目录/e/docker/mysql/data/db
      - "./mysql/manager/data:/var/lib/mysql"
      #容器的配置目录挂载到host物理机目录/e/docker/mysql/data/conf
      - "./conf/my.cnf:/etc/mysql/conf.d/mysqlutf8.cnf"
    network_mode: "host"
    #networks:
    #  - webase_network

  mysql-sign:
    #构建mysql镜像
    image: mysql:5.7
    container_name: mysql-sign-server # 容器名
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #root管理员用户密码
      MYSQL_DATABASE: webasesign
      MYSQL_USER: dbUsername
      MYSQL_PASSWORD: dbPassword
    ports:
      - '3307:3306'  #host物理直接映射端口为3306
    volumes:
      #mysql数据库挂载到host物理机目录/e/docker/mysql/data/db
      - "./mysql/sign/data:/var/lib/mysql"
      #容器的配置目录挂载到host物理机目录/e/docker/mysql/data/conf
      - "./conf/my.cnf:/etc/mysql/conf.d/mysqlutf8.cnf"
    network_mode: "host"
    #networks:
    #  - webase_network

  web:
    image: yuanmomo/webase-web:${WEBASE_DOCKER_TAG}
    container_name: webase-web
    environment:
      - ACME_AGREE=true
    network_mode: "host"
    depends_on:
      - "webase-node-manager"
    volumes:
      - ./conf/Caddyfile:/etc/Caddyfile
      - ./caddy/:/root/.caddy/
      - ./log/caddy:/var/log/caddy

  node0:
    image: fiscoorg/fiscobcos:${BUILD_VERSION}
    container_name: rootfisconodes127.0.0.1node0
    working_dir: /data
    command: -c config.ini
    network_mode: "host"
    volumes:
      - ./fisco/nodes/127.0.0.1/node0:/data

  node1:
    image: fiscoorg/fiscobcos:${BUILD_VERSION}
    container_name: rootfisconodes127.0.0.1node1
    working_dir: /data
    command: -c config.ini
    network_mode: "host"
    depends_on:
      - "node0"
    volumes:
      - ./fisco/nodes/127.0.0.1/node1:/data

  node2:
    image: fiscoorg/fiscobcos:${BUILD_VERSION}
    container_name: rootfisconodes127.0.0.1node2
    working_dir: /data
    command: -c config.ini
    network_mode: "host"
    depends_on:
      - "node1"
    volumes:
      - ./fisco/nodes/127.0.0.1/node2:/data
  node3:
    image: fiscoorg/fiscobcos:${BUILD_VERSION}
    container_name: rootfisconodes127.0.0.1node3
    working_dir: /data
    command: -c config.ini
    network_mode: "host"
    depends_on:
      - "node2"
    volumes:
      - ./fisco/nodes/127.0.0.1/node3:/data


