#constants
spring:
  datasource:
    url: jdbc:h2:file:/dist/h2/webasefront;DB_CLOSE_ON_EXIT=FALSE
sdk:
  encryptType: 0 # 1:guomi, 0:standard
constant:
  keyServer: 127.0.0.1:5004 # sign服务的IP:Port（单个）

