#constants
sdk:
  encryptType: 0 # 1:guomi, 0:standard
spring:
  datasource:
    # 数据库连接信息
    url: jdbc:mysql://127.0.0.1:3307/webasesign?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
