# build command :
#   cat Dockerfile-Front | docker build -t yuanmomo/webase-front:1.3.1 -f - https://github.com/CodingCattwo/WeBASE-Front.git#dev131
#
# run command :
# docker run --rm --name "front" --network=host -v /root/fisco/nodes/127.0.0.1/sdk/ca.crt:/dist/conf/ca.crt -v /root/fisco/nodes/127.0.0.1/sdk/node.key:/dist/conf/node.key  -v /root/fisco/nodes/127.0.0.1/sdk/node.crt:/dist/conf/node.crt yuanmomo/webase-front:1.3.1
#

FROM gradle:6.4.0-jdk8 as builder
LABEL maintainer yuanhongbin9090@gmail.com

WORKDIR /code

# copy source code
COPY src src
COPY build.gradle build.gradle

# build
RUN gradle build -x test


FROM openjdk:8-jdk-alpine as prod

RUN apk --no-cache add bash curl wget

COPY --from=builder /code/dist/lib                  /dist/lib
COPY --from=builder /code/dist/conf_template        /dist/conf
COPY --from=builder /code/dist/apps                 /dist/apps

EXPOSE 5002

ENV CLASSPATH "/dist/conf/:/dist/apps/*:/dist/lib/*"

ENV JAVA_OPTS " -server -Dfile.encoding=UTF-8 -Xmx256m -Xms256m -Xmn128m -Xss512k -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/log/heap_error.log  -XX:+UseG1GC -XX:MaxGCPauseMillis=200 "
ENV APP_MAIN "com.webank.webase.front.Application"

# start commond
ENTRYPOINT java ${JAVA_OPTS} -Djdk.tls.namedGroups="secp256k1", -Duser.timezone="Asia/Shanghai" -Djava.security.egd=file:/dev/./urandom, -Djava.library.path=/dist/conf -cp ${CLASSPATH}  ${APP_MAIN}
