# build command :
#   cat Dockerfile-MySQL-guomi | docker build -t yuanmomo/webase-mysql:1.3.2 -f - https://github.com/WeBankFinTech/WeBASE-Node-Manager.git#dev131
#

FROM mysql:5.7
LABEL maintainer yuanhongbin9090@gmail.com

WORKDIR /code

# copy source code
COPY script/webase-ddl.sql /docker-entrypoint-initdb.d/
COPY script/gm/*.sql /docker-entrypoint-initdb.d/
