# build command :
#   cat Dockerfile-MySQL | docker build -t yuanmomo/webase-node-manager:1.3.1 -f - https://github.com/CodingCattwo/WeBASE-Node-Manager.git#dev131
#

FROM mysql:5.7
LABEL maintainer yuanhongbin9090@gmail.com

WORKDIR /code

# copy source code
COPY script/*.sql /docker-entrypoint-initdb.d/
