# build command :
#   cat Dockerfile-Web | docker build -t yuanmomo/webase-web:1.3.1 -f - https://github.com/WeBankFinTech/WeBASE-Web.git#bsn

FROM abiosoft/caddy:latest
LABEL maintainer yuanhongbin9090@gmail.com

RUN apk --no-cache add bash curl wget

COPY  dist  /dist/

EXPOSE 5000


